name: Super clone
run-name: ${{github.actor}} is super cloning
on:
  workflow_dispatch:
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          path: .emacs.d

      - name: Installing emacs
        run: | 
          sudo snap install emacs --classic

      - name: Emacs version
        run: |
          emacs --version

      - name: Downloading from elpa
        run: |
          ln -s ${{github.workspace}}/.emacs.d "$HOME"/.emacs.d
          emacs --kill --fg-daemon --debug-init

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: emacs_d
          path: |
            .emacs.d
            !.emacs.d/eln-cache/
          if-no-files-found: error
          include-hidden-files: true
